Update variables in `inputref.py`
eWaterCycle/era5cli pull request #84
Opened 2021-04-19 14:45 UTC by bvreede

The current variables in `inputref.py` do not reflect the current state of the API at CDS. The file has been amended to include more variables, both hourly and monthly, that are available for the ERA5 datasets.

Three variables were in our reference, but not part of the selection at CDS:
-    `altimeter_corrected_wave_height`
-    `altimeter_range_relative_correction`
-    `altimeter_wave_height`
I have left them in, but propose that we take another look at the current set of variables, perhaps consider how we can automate this workflow so we have an up-to-date set of variables in the tool (see #83), and/or consider how much we want era5cli to 'protect' the user from framing an impossible request.

Closes #77.

2021-04-19 15:05 UTC, stefsmeets requested changes
So, if I understand correctly, there is a master list of variables: `SLVARS`, and then an additional list of variables which are missing from the master list, so that `HOURLY_VARS == SLVARS - MISSING_HOURLY_VARS`?

Then, should `fetch.py` also be updated somewhere here to make use of this new `MISSING_HOURLY_VARS` dict?

2021-04-20 04:21 UTC, bvreede commented
Thanks @stefsmeets, well spotted!

I chose not to do this, as the purpose of `MISSING_HOURLY_VARS` at the moment is purely for documentation. Implementing this list will have effects on the cli calls done that include these variables, and it might even break some workflows; I have not checked whether these variables actually do return data, but they could; implementing this list in the same way as done with `MISSING_MONTHLY_VARS` will stop the request from being formed altogether. There must be a reason why they're gone from CDS, but e.g. I did find other variables that were no longer on the list on the website, but when used in an era5cli call still return data.

As for the variable list itself: there is a bigger problem there, too, in that this is a (currently purely manual) update that should be done frequently with CDS updates. In other words: this list of variables needs to be refactored into an automated workflow (see also #83), so I did not want to spend too much energy into implementing any downstream refactoring that may become obsolete soon.

The main point for this PR is to make sure there are no bugs in the upcoming release, so I tried to match the variable lists with info on CDS, and added the variable for documentation purposes. I've now tried to make this clearer in the code itself.

2021-04-20 04:28 UTC, bvreede commented on era5cli/inputref.py
> +
Yep thanks! Done!

2021-04-20 07:26 UTC, stefsmeets approved these changes
Alright, just making sure it was not an oversight! 🚀

2021-04-20 08:59 UTC, merged